version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres:9.6.15-alpine
    env_file:
      - ./src/config/env/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    env_file:
      - ./src/config/env/.env.production
    ports:
      - "6379:6379"
    networks:
      - app-network

  serv:
    env_file:
      - ./src/config/env/.env.production
    build:
      context: '.'
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - app-network


volumes:
  postgres_data:
    external: true
